0:
  Cost: 0.5
  Delay: 1
  ID: c0
  Pos:
  - 85
  - 22
  Throughput: 125
1:
  Cost: 0.5
  Delay: 1
  ID: c1
  Pos:
  - 35
  - 30
  Throughput: 125
2:
  Cost: 0.5
  Delay: 2
  ID: c2
  Pos:
  - 4
  - 45
  Throughput: 100
3:
  Cost: 0.5
  Delay: 1
  ID: c3
  Pos:
  - 35
  - 87
  Throughput: 125
4:
  Cost: 0.5
  Delay: 1
  ID: c4
  Pos:
  - 68
  - 60
  Throughput: 125
