0:
  Cost: 0.5
  Delay: 1
  ID: c0
  Pos:
  - 59.0
  - 52.0
  Throughput: 125
1:
  Cost: 0.5
  Delay: 1
  ID: c1
  Pos:
  - 6.0
  - 74.0
  Throughput: 125
2:
  Cost: 0.5
  Delay: 1
  ID: c2
  Pos:
  - 49.0
  - 79.0
  Throughput: 125
3:
  Cost: 0.5
  Delay: 1
  ID: c3
  Pos:
  - 58.0
  - 13.0
  Throughput: 125
4:
  Cost: 0.5
  Delay: 1
  ID: c4
  Pos:
  - 30.0
  - 100.0
  Throughput: 125
