0:
  Cost: 0.5
  Delay: 1
  ID: c0
  Pos:
  - 87.0
  - 86.0
  Throughput: 175
1:
  Cost: 0.5
  Delay: 2
  ID: c1
  Pos:
  - 28.0
  - 23.0
  Throughput: 100
2:
  Cost: 0.5
  Delay: 1
  ID: c2
  Pos:
  - 33.0
  - 89.0
  Throughput: 175
3:
  Cost: 0.5
  Delay: 2
  ID: c3
  Pos:
  - 99.0
  - 24.0
  Throughput: 150
4:
  Cost: 0.5
  Delay: 1
  ID: c4
  Pos:
  - 48.0
  - 49.0
  Throughput: 175
