0:
  Cost: 0.5
  Delay: 2
  ID: c0
  Pos:
  - 19
  - 30
  Throughput: 100
1:
  Cost: 0.5
  Delay: 1
  ID: c1
  Pos:
  - 81
  - 63
  Throughput: 125
2:
  Cost: 0.5
  Delay: 1
  ID: c2
  Pos:
  - 14
  - 80
  Throughput: 125
3:
  Cost: 0.5
  Delay: 2
  ID: c3
  Pos:
  - 62
  - 11
  Throughput: 150
4:
  Cost: 0.5
  Delay: 2
  ID: c4
  Pos:
  - 49
  - 59
  Throughput: 100
