0:
  Cost: 0.5
  Delay: 2
  ID: c0
  Pos:
  - 65
  - 20
  Throughput: 100
1:
  Cost: 0.5
  Delay: 2
  ID: c1
  Pos:
  - 71
  - 63
  Throughput: 150
2:
  Cost: 0.5
  Delay: 1
  ID: c2
  Pos:
  - 22
  - 29
  Throughput: 175
3:
  Cost: 0.5
  Delay: 1
  ID: c3
  Pos:
  - 22
  - 79
  Throughput: 175
4:
  Cost: 0.5
  Delay: 1
  ID: c4
  Pos:
  - 71
  - 96
  Throughput: 175
