0:
  Cost: 7.0
  Delay: 6
  ID: c1
  Pos:
  - 23
  - 25
  Throughput: 3
1:
  Cost: 7.0
  Delay: 5
  ID: c2
  Pos:
  - 38
  - 95
  Throughput: 4
2:
  Cost: 3.0
  Delay: 35
  ID: c3
  Pos:
  - 47
  - 98
  Throughput: 24
