0:
  Cost: 0.8
  Delay: 1
  ID: s0
  Pos:
  - 63.0
  - 54.0
  Throughput: 20
1:
  Cost: 0.8
  Delay: 1
  ID: s1
  Pos:
  - 26.0
  - 100.0
  Throughput: 20
2:
  Cost: 0.8
  Delay: 1
  ID: s2
  Pos:
  - 61.0
  - 71.0
  Throughput: 20
3:
  Cost: 0.5
  Delay: 2
  ID: s3
  Pos:
  - 37.0
  - 27.0
  Throughput: 10
4:
  Cost: 0.8
  Delay: 1
  ID: s4
  Pos:
  - 64.0
  - 66.0
  Throughput: 20
5:
  Cost: 0.9
  Delay: 1
  ID: s5
  Pos:
  - 60.0
  - 88.0
  Throughput: 25
6:
  Cost: 0.9
  Delay: 1
  ID: s6
  Pos:
  - 71.0
  - 57.0
  Throughput: 25
7:
  Cost: 0.9
  Delay: 1
  ID: s7
  Pos:
  - 35.0
  - 78.0
  Throughput: 25
8:
  Cost: 0.5
  Delay: 2
  ID: s8
  Pos:
  - 1.0
  - 86.0
  Throughput: 10
9:
  Cost: 0.9
  Delay: 1
  ID: s9
  Pos:
  - 55.0
  - 4.0
  Throughput: 25
10:
  Cost: 0.9
  Delay: 1
  ID: s10
  Pos:
  - 55.0
  - 76.0
  Throughput: 25
11:
  Cost: 0.9
  Delay: 1
  ID: s11
  Pos:
  - 57.0
  - 93.0
  Throughput: 25
12:
  Cost: 0.9
  Delay: 1
  ID: s12
  Pos:
  - 91.0
  - 5.0
  Throughput: 25
13:
  Cost: 0.6
  Delay: 2
  ID: s13
  Pos:
  - 5.0
  - 48.0
  Throughput: 15
14:
  Cost: 0.5
  Delay: 2
  ID: s14
  Pos:
  - 77.0
  - 56.0
  Throughput: 10
15:
  Cost: 0.8
  Delay: 1
  ID: s15
  Pos:
  - 14.0
  - 74.0
  Throughput: 20
16:
  Cost: 0.5
  Delay: 2
  ID: s16
  Pos:
  - 35.0
  - 71.0
  Throughput: 10
17:
  Cost: 0.5
  Delay: 2
  ID: s17
  Pos:
  - 9.0
  - 90.0
  Throughput: 10
18:
  Cost: 0.6
  Delay: 2
  ID: s18
  Pos:
  - 39.0
  - 34.0
  Throughput: 15
19:
  Cost: 0.8
  Delay: 1
  ID: s19
  Pos:
  - 4.0
  - 72.0
  Throughput: 20
20:
  Cost: 0.6
  Delay: 2
  ID: s20
  Pos:
  - 44.0
  - 56.0
  Throughput: 15
21:
  Cost: 0.8
  Delay: 1
  ID: s21
  Pos:
  - 41.0
  - 82.0
  Throughput: 20
22:
  Cost: 0.5
  Delay: 2
  ID: s22
  Pos:
  - 52.0
  - 17.0
  Throughput: 10
23:
  Cost: 0.9
  Delay: 1
  ID: s23
  Pos:
  - 35.0
  - 100.0
  Throughput: 25
24:
  Cost: 0.9
  Delay: 1
  ID: s24
  Pos:
  - 61.0
  - 45.0
  Throughput: 25
