0:
  Cost: 0.5
  Delay: 2
  ID: s0
  Pos:
  - 4
  - 36
  Throughput: 10
1:
  Cost: 0.8
  Delay: 1
  ID: s1
  Pos:
  - 61
  - 49
  Throughput: 20
2:
  Cost: 0.6
  Delay: 2
  ID: s2
  Pos:
  - 20
  - 25
  Throughput: 15
3:
  Cost: 0.9
  Delay: 1
  ID: s3
  Pos:
  - 45
  - 21
  Throughput: 25
4:
  Cost: 0.9
  Delay: 1
  ID: s4
  Pos:
  - 65
  - 43
  Throughput: 25
5:
  Cost: 0.5
  Delay: 2
  ID: s5
  Pos:
  - 53
  - 67
  Throughput: 10
6:
  Cost: 0.9
  Delay: 1
  ID: s6
  Pos:
  - 13
  - 65
  Throughput: 25
7:
  Cost: 0.5
  Delay: 2
  ID: s7
  Pos:
  - 34
  - 96
  Throughput: 10
8:
  Cost: 0.5
  Delay: 2
  ID: s8
  Pos:
  - 88
  - 2
  Throughput: 10
9:
  Cost: 0.8
  Delay: 1
  ID: s9
  Pos:
  - 32
  - 35
  Throughput: 20
10:
  Cost: 0.8
  Delay: 1
  ID: s10
  Pos:
  - 25
  - 91
  Throughput: 20
11:
  Cost: 0.5
  Delay: 2
  ID: s11
  Pos:
  - 93
  - 83
  Throughput: 10
12:
  Cost: 0.5
  Delay: 2
  ID: s12
  Pos:
  - 89
  - 40
  Throughput: 10
13:
  Cost: 0.6
  Delay: 2
  ID: s13
  Pos:
  - 64
  - 6
  Throughput: 15
14:
  Cost: 0.6
  Delay: 2
  ID: s14
  Pos:
  - 47
  - 81
  Throughput: 15
15:
  Cost: 0.8
  Delay: 1
  ID: s15
  Pos:
  - 1
  - 51
  Throughput: 20
16:
  Cost: 0.8
  Delay: 1
  ID: s16
  Pos:
  - 90
  - 31
  Throughput: 20
17:
  Cost: 0.9
  Delay: 1
  ID: s17
  Pos:
  - 3
  - 39
  Throughput: 25
18:
  Cost: 0.8
  Delay: 1
  ID: s18
  Pos:
  - 43
  - 46
  Throughput: 20
19:
  Cost: 0.9
  Delay: 1
  ID: s19
  Pos:
  - 47
  - 76
  Throughput: 25
20:
  Cost: 0.9
  Delay: 1
  ID: s20
  Pos:
  - 97
  - 49
  Throughput: 25
21:
  Cost: 0.8
  Delay: 1
  ID: s21
  Pos:
  - 82
  - 8
  Throughput: 20
22:
  Cost: 0.6
  Delay: 2
  ID: s22
  Pos:
  - 23
  - 92
  Throughput: 15
23:
  Cost: 0.8
  Delay: 1
  ID: s23
  Pos:
  - 36
  - 24
  Throughput: 20
24:
  Cost: 0.6
  Delay: 2
  ID: s24
  Pos:
  - 3
  - 38
  Throughput: 15
