0:
  Cost: 0.6
  Delay: 2
  ID: s0
  Pos:
  - 21
  - 36
  Throughput: 15
1:
  Cost: 0.5
  Delay: 2
  ID: s1
  Pos:
  - 14
  - 49
  Throughput: 10
2:
  Cost: 0.6
  Delay: 2
  ID: s2
  Pos:
  - 19
  - 21
  Throughput: 15
3:
  Cost: 0.6
  Delay: 2
  ID: s3
  Pos:
  - 65
  - 12
  Throughput: 15
4:
  Cost: 0.6
  Delay: 2
  ID: s4
  Pos:
  - 43
  - 77
  Throughput: 15
5:
  Cost: 0.5
  Delay: 2
  ID: s5
  Pos:
  - 38
  - 27
  Throughput: 10
6:
  Cost: 0.9
  Delay: 1
  ID: s6
  Pos:
  - 24
  - 75
  Throughput: 25
7:
  Cost: 0.5
  Delay: 2
  ID: s7
  Pos:
  - 45
  - 58
  Throughput: 10
8:
  Cost: 0.9
  Delay: 1
  ID: s8
  Pos:
  - 85
  - 62
  Throughput: 25
9:
  Cost: 0.6
  Delay: 2
  ID: s9
  Pos:
  - 22
  - 29
  Throughput: 15
10:
  Cost: 0.6
  Delay: 2
  ID: s10
  Pos:
  - 51
  - 43
  Throughput: 15
11:
  Cost: 0.8
  Delay: 1
  ID: s11
  Pos:
  - 81
  - 86
  Throughput: 20
12:
  Cost: 0.6
  Delay: 2
  ID: s12
  Pos:
  - 73
  - 21
  Throughput: 15
13:
  Cost: 0.8
  Delay: 1
  ID: s13
  Pos:
  - 61
  - 3
  Throughput: 20
14:
  Cost: 0.6
  Delay: 2
  ID: s14
  Pos:
  - 50
  - 9
  Throughput: 15
15:
  Cost: 0.5
  Delay: 2
  ID: s15
  Pos:
  - 91
  - 64
  Throughput: 10
16:
  Cost: 0.6
  Delay: 2
  ID: s16
  Pos:
  - 19
  - 82
  Throughput: 15
17:
  Cost: 0.5
  Delay: 2
  ID: s17
  Pos:
  - 73
  - 62
  Throughput: 10
18:
  Cost: 0.6
  Delay: 2
  ID: s18
  Pos:
  - 1
  - 86
  Throughput: 15
19:
  Cost: 0.5
  Delay: 2
  ID: s19
  Pos:
  - 26
  - 97
  Throughput: 10
20:
  Cost: 0.5
  Delay: 2
  ID: s20
  Pos:
  - 60
  - 59
  Throughput: 10
21:
  Cost: 0.9
  Delay: 1
  ID: s21
  Pos:
  - 2
  - 22
  Throughput: 25
22:
  Cost: 0.8
  Delay: 1
  ID: s22
  Pos:
  - 75
  - 45
  Throughput: 20
23:
  Cost: 0.9
  Delay: 1
  ID: s23
  Pos:
  - 86
  - 63
  Throughput: 25
24:
  Cost: 0.6
  Delay: 2
  ID: s24
  Pos:
  - 0
  - 61
  Throughput: 15
