0:
  Cost: 0.8
  Delay: 1
  ID: s0
  Pos:
  - 61
  - 61
  Throughput: 20
1:
  Cost: 0.8
  Delay: 1
  ID: s1
  Pos:
  - 28
  - 13
  Throughput: 20
2:
  Cost: 0.6
  Delay: 2
  ID: s2
  Pos:
  - 40
  - 83
  Throughput: 15
3:
  Cost: 0.9
  Delay: 1
  ID: s3
  Pos:
  - 12
  - 96
  Throughput: 25
4:
  Cost: 0.9
  Delay: 1
  ID: s4
  Pos:
  - 57
  - 19
  Throughput: 25
5:
  Cost: 0.8
  Delay: 1
  ID: s5
  Pos:
  - 0
  - 83
  Throughput: 20
6:
  Cost: 0.8
  Delay: 1
  ID: s6
  Pos:
  - 56
  - 75
  Throughput: 20
7:
  Cost: 0.9
  Delay: 1
  ID: s7
  Pos:
  - 24
  - 72
  Throughput: 25
8:
  Cost: 0.6
  Delay: 2
  ID: s8
  Pos:
  - 65
  - 100
  Throughput: 15
9:
  Cost: 0.8
  Delay: 1
  ID: s9
  Pos:
  - 62
  - 19
  Throughput: 20
10:
  Cost: 0.9
  Delay: 1
  ID: s10
  Pos:
  - 64
  - 95
  Throughput: 25
11:
  Cost: 0.6
  Delay: 2
  ID: s11
  Pos:
  - 27
  - 57
  Throughput: 15
12:
  Cost: 0.6
  Delay: 2
  ID: s12
  Pos:
  - 80
  - 46
  Throughput: 15
13:
  Cost: 0.6
  Delay: 2
  ID: s13
  Pos:
  - 7
  - 41
  Throughput: 15
14:
  Cost: 0.9
  Delay: 1
  ID: s14
  Pos:
  - 37
  - 28
  Throughput: 25
15:
  Cost: 0.9
  Delay: 1
  ID: s15
  Pos:
  - 87
  - 73
  Throughput: 25
16:
  Cost: 0.8
  Delay: 1
  ID: s16
  Pos:
  - 23
  - 41
  Throughput: 20
17:
  Cost: 0.5
  Delay: 2
  ID: s17
  Pos:
  - 73
  - 91
  Throughput: 10
18:
  Cost: 0.9
  Delay: 1
  ID: s18
  Pos:
  - 84
  - 21
  Throughput: 25
19:
  Cost: 0.9
  Delay: 1
  ID: s19
  Pos:
  - 14
  - 12
  Throughput: 25
20:
  Cost: 0.8
  Delay: 1
  ID: s20
  Pos:
  - 68
  - 32
  Throughput: 20
21:
  Cost: 0.8
  Delay: 1
  ID: s21
  Pos:
  - 58
  - 9
  Throughput: 20
22:
  Cost: 0.6
  Delay: 2
  ID: s22
  Pos:
  - 33
  - 85
  Throughput: 15
23:
  Cost: 0.9
  Delay: 1
  ID: s23
  Pos:
  - 82
  - 98
  Throughput: 25
24:
  Cost: 0.8
  Delay: 1
  ID: s24
  Pos:
  - 26
  - 40
  Throughput: 20
