0:
  Cost: 0.8
  Delay: 1
  ID: s0
  Pos:
  - 8
  - 61
  Throughput: 20
1:
  Cost: 0.6
  Delay: 2
  ID: s1
  Pos:
  - 76
  - 52
  Throughput: 15
2:
  Cost: 0.9
  Delay: 1
  ID: s2
  Pos:
  - 59
  - 87
  Throughput: 25
3:
  Cost: 0.5
  Delay: 2
  ID: s3
  Pos:
  - 11
  - 10
  Throughput: 10
4:
  Cost: 0.9
  Delay: 1
  ID: s4
  Pos:
  - 96
  - 66
  Throughput: 25
5:
  Cost: 0.5
  Delay: 2
  ID: s5
  Pos:
  - 55
  - 38
  Throughput: 10
6:
  Cost: 0.5
  Delay: 2
  ID: s6
  Pos:
  - 7
  - 22
  Throughput: 10
7:
  Cost: 0.8
  Delay: 1
  ID: s7
  Pos:
  - 46
  - 51
  Throughput: 20
8:
  Cost: 0.5
  Delay: 2
  ID: s8
  Pos:
  - 18
  - 48
  Throughput: 10
9:
  Cost: 0.9
  Delay: 1
  ID: s9
  Pos:
  - 0
  - 67
  Throughput: 25
10:
  Cost: 0.6
  Delay: 2
  ID: s10
  Pos:
  - 20
  - 96
  Throughput: 15
11:
  Cost: 0.6
  Delay: 2
  ID: s11
  Pos:
  - 84
  - 41
  Throughput: 15
12:
  Cost: 0.6
  Delay: 2
  ID: s12
  Pos:
  - 98
  - 16
  Throughput: 15
13:
  Cost: 0.6
  Delay: 2
  ID: s13
  Pos:
  - 61
  - 64
  Throughput: 15
14:
  Cost: 0.5
  Delay: 2
  ID: s14
  Pos:
  - 80
  - 44
  Throughput: 10
15:
  Cost: 0.6
  Delay: 2
  ID: s15
  Pos:
  - 63
  - 66
  Throughput: 15
16:
  Cost: 0.6
  Delay: 2
  ID: s16
  Pos:
  - 18
  - 95
  Throughput: 15
17:
  Cost: 0.9
  Delay: 1
  ID: s17
  Pos:
  - 34
  - 78
  Throughput: 25
18:
  Cost: 0.6
  Delay: 2
  ID: s18
  Pos:
  - 38
  - 44
  Throughput: 15
19:
  Cost: 0.5
  Delay: 2
  ID: s19
  Pos:
  - 83
  - 8
  Throughput: 10
20:
  Cost: 0.8
  Delay: 1
  ID: s20
  Pos:
  - 73
  - 9
  Throughput: 20
21:
  Cost: 0.5
  Delay: 2
  ID: s21
  Pos:
  - 46
  - 42
  Throughput: 10
22:
  Cost: 0.8
  Delay: 1
  ID: s22
  Pos:
  - 17
  - 97
  Throughput: 20
23:
  Cost: 0.9
  Delay: 1
  ID: s23
  Pos:
  - 40
  - 99
  Throughput: 25
24:
  Cost: 0.5
  Delay: 2
  ID: s24
  Pos:
  - 61
  - 23
  Throughput: 10
